# Generated by Django 4.2.4 on 2024-04-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0009_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
