# Generated by Django 4.2.4 on 2024-04-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0010_like_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='fotografia',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
