# Generated by Django 4.2.4 on 2024-04-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0013_alter_fotografia_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
