# Generated by Django 4.2.4 on 2024-02-22 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galeria', '0008_alter_fotografia_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('post1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galeria.fotografia')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comentario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
